language: node_js
os: linux
dist: jammy
node_js:
- '18'
sudo: required
notifications:
  email: false
install:
  - npm ci
script: npm run lint && npm run test && npx codecov && npm run deploy && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
    global:
    - REPO="git@github.com:RedHatInsights/rbac-frontend-deploy.git"
    - REPO_DIR="rbac-frontend-deploy"
    - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
